In [1]:
import pandas as pd

# Employees dataset
employees = pd.DataFrame({
    'emp_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'emp_name': [
        'Arun', 'Bala', 'Charan', 'Deepa', 'Eshan',
        'Farah', 'Gokul', 'Hari', 'Isha', 'Jeevan'
    ],
    'department_id': [
        101, 102, 103, 104, 101, 102, 105, 106, None, 103
    ],
    'salary': [
        30000, 45000, 50000, 35000, 60000,
        65000, 40000, 55000, 32000, 48000
    ],
    'city': [
        '5', '5', '6', '6', None, None, '5', '6', '5', '6'
    ]
})

# Departments dataset
departments = pd.DataFrame({
    'department_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'department_name': [
        'HR', 'IT', 'Finance', 'Marketing', 'Sales',
        'Analytics', 'Support', 'Research', 'Security', 'Operations'
    ],
    'manager_name': [
        'Bangalore', 'Chennai', 'Mumbai', 'Pune', 'Delhi',
        'Hyderabad', 'Kolkata', 'Bangalore', 'Chennai', 'Mumbai'
    ]
})

# Display datasets
print("EMPLOYEES DATASET")
display(employees)

print("DEPARTMENTS DATASET")
display(departments)

EMPLOYEES DATASET

   emp_id emp_name  department_id  salary  city
0       1     Arun          101.0   30000     5
1       2     Bala          102.0   45000     5
2       3   Charan          103.0   50000     6
3       4    Deepa          104.0   35000     6
4       5    Eshan          101.0   60000  None
5       6    Farah          102.0   65000  None
6       7    Gokul          105.0   40000     5
7       8     Hari          106.0   55000     6
8       9     Isha            NaN   32000     5
9      10   Jeevan          103.0   48000     6

DEPARTMENTS DATASET

   department_id department_name manager_name
0            101              HR    Bangalore
1            102              IT      Chennai
2            103         Finance       Mumbai
3            104       Marketing         Pune
4            105           Sales        Delhi
5            106       Analytics    Hyderabad
6            107         Support      Kolkata
7            108        Research    Bangalore
8            109        Security      Chennai
9            110      Operations       Mumbai

In [4]:
Table_inner_join = pd.merge(
    employees,
    departments,
    on='department_id',
    how='inner'
)

display(Table_inner_join)

   emp_id emp_name  department_id  salary  city department_name manager_name
0       1     Arun          101.0   30000     5              HR    Bangalore
1       2     Bala          102.0   45000     5              IT      Chennai
2       3   Charan          103.0   50000     6         Finance       Mumbai
3       4    Deepa          104.0   35000     6       Marketing         Pune
4       5    Eshan          101.0   60000  None              HR    Bangalore
5       6    Farah          102.0   65000  None              IT      Chennai
6       7    Gokul          105.0   40000     5           Sales        Delhi
7       8     Hari          106.0   55000     6       Analytics    Hyderabad
8      10   Jeevan          103.0   48000     6         Finance       Mumbai

In [5]:
table_left_join = pd.merge(
    employees,
    departments,
    on='department_id',
    how='left'
)

display(table_left_join)

   emp_id emp_name  department_id  salary  city department_name manager_name
0       1     Arun          101.0   30000     5              HR    Bangalore
1       2     Bala          102.0   45000     5              IT      Chennai
2       3   Charan          103.0   50000     6         Finance       Mumbai
3       4    Deepa          104.0   35000     6       Marketing         Pune
4       5    Eshan          101.0   60000  None              HR    Bangalore
5       6    Farah          102.0   65000  None              IT      Chennai
6       7    Gokul          105.0   40000     5           Sales        Delhi
7       8     Hari          106.0   55000     6       Analytics    Hyderabad
8       9     Isha            NaN   32000     5             NaN          NaN
9      10   Jeevan          103.0   48000     6         Finance       Mumbai

In [6]:
table_right_join = pd.merge(
    employees,
    departments,
    on='department_id',
    how='right'
)

display(table_right_join)

    emp_id emp_name  department_id   salary  city department_name manager_name
0      1.0     Arun          101.0  30000.0     5              HR    Bangalore
1      5.0    Eshan          101.0  60000.0  None              HR    Bangalore
2      2.0     Bala          102.0  45000.0     5              IT      Chennai
3      6.0    Farah          102.0  65000.0  None              IT      Chennai
4      3.0   Charan          103.0  50000.0     6         Finance       Mumbai
5     10.0   Jeevan          103.0  48000.0     6         Finance       Mumbai
6      4.0    Deepa          104.0  35000.0     6       Marketing         Pune
7      7.0    Gokul          105.0  40000.0     5           Sales        Delhi
8      8.0     Hari          106.0  55000.0     6       Analytics    Hyderabad
9      NaN      NaN          107.0      NaN   NaN         Support      Kolkata
10     NaN      NaN          108.0      NaN   NaN        Research    Bangalore
11     NaN      NaN          109.0      NaN   NaN        Security      Chennai
12     NaN      NaN          110.0      NaN   NaN      Operations       Mumbai

In [7]:
table_outer_join = pd.merge(
    employees,
    departments,
    on='department_id',
    how='outer',
    indicator=True
)

display(table_outer_join)

,emp_id,emp_name,department_id,salary,city,department_name,manager_name,_merge
0,1.0,Arun,101.0,30000.0,5,HR,Bangalore,both
1,5.0,Eshan,101.0,60000.0,None,HR,Bangalore,both
2,2.0,Bala,102.0,45000.0,5,IT,Chennai,both
3,6.0,Farah,102.0,65000.0,None,IT,Chennai,both
4,3.0,Charan,103.0,50000.0,6,Finance,Mumbai,both
5,10.0,Jeevan,103.0,48000.0,6,Finance,Mumbai,both
6,4.0,Deepa,104.0,35000.0,6,Marketing,Pune,both
7,7.0,Gokul,105.0,40000.0,5,Sales,Delhi,both
8,8.0,Hari,106.0,55000.0,6,Analytics,Hyderabad,both
9,NaN,NaN,107.0,NaN,NaN,Support,Kolkata,right_only
10,NaN,NaN,108.0,NaN,NaN,Research,Bangalore,right_only
11,NaN,NaN,109.0,NaN,NaN,Security,Chennai,right_only
12,NaN,NaN,110.0,NaN,NaN,Operations,Mumbai,right_only
13,9.0,Isha,NaN,32000.0,5,NaN,NaN,left_only

We can join the table using pd.merge and mention in "how=" for left,right,inner and outer join

In [8]:
sales = pd.DataFrame({
    'region': ['North', 'South', 'East', 'West', 'North',
               'South', 'East', 'West', 'North', 'South'],
    'product': ['Laptop', 'Mobile', 'Laptop', 'Mobile', 'Mobile',
                'Laptop', 'Mobile', 'Laptop', 'Laptop', 'Mobile'],
    'sales': [50000, 30000, 45000, 25000, 20000,
              55000, 35000, 60000, 40000, 28000]
})

display(sales)

  region product  sales
0  North  Laptop  50000
1  South  Mobile  30000
2   East  Laptop  45000
3   West  Mobile  25000
4  North  Mobile  20000
5  South  Laptop  55000
6   East  Mobile  35000
7   West  Laptop  60000
8  North  Laptop  40000
9  South  Mobile  28000

Create a pivot for sales table on two product Laptop and mobile. summed the values of sales according to its region

In [9]:
pivot_table = pd.pivot_table(
    sales,
    values='sales',
    index='region',
    columns='product',
    aggfunc='sum',
    fill_value=0
)

display(pivot_table)

product  Laptop  Mobile
region
East      45000   35000
North     90000   20000
South     55000   58000
West      60000   25000

Pivot table looks similar to groupby function in SQL

In [13]:
sales = pd.DataFrame({
    'region': ['North', 'South', 'East'],
    'Laptop': [50000, 60000, 45000],
    'Mobile': [30000, 40000, 35000],
    'Tablet': [20000, 25000, 15000]
})

display(sales)

  region  Laptop  Mobile  Tablet
0  North   50000   30000   20000
1  South   60000   40000   25000
2   East   45000   35000   15000

In [11]:
long_sales = pd.melt(
    sales,
    id_vars=['region'],
    var_name='product',
    value_name='sales'
)

display(long_sales)

  region product  sales
0  North  Laptop  50000
1  South  Laptop  60000
2   East  Laptop  45000
3  North  Mobile  30000
4  South  Mobile  40000
5   East  Mobile  35000
6  North  Tablet  20000
7  South  Tablet  25000
8   East  Tablet  15000

Chainning multiple pandas operation this query is to find out "sales greater than 30,000 according to their region"

In [14]:
result = (
    long_sales
    .query("sales > 20000")
    .query("product == 'Laptop'")
    .groupby('region')['sales']
    .sum()
)
display(result)

region
East     45000
North    50000
South    60000
Name: sales, dtype: int64