In [1]:
import pandas as pd

In [2]:
dataset= pd.read_csv('Sample data.csv')

In [8]:
dataset.head()

   emp_id emp_name region  sales_amount
0       1     Arun  North        5000.0
1       2     Bala  North        9000.0
2       3   Charan  North        7000.0
3       4    Divya  North        4000.0
4       5     Esha  South        6000.0

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   emp_id        15 non-null     int64
 1   emp_name      15 non-null     object
 2   region        15 non-null     object
 3   sales_amount  15 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 612.0+ bytes

In [10]:
dataset.describe()

          emp_id  sales_amount
count  15.000000     15.000000
mean    8.000000   6800.000000
std     4.472136   2366.431913
min     1.000000   3000.000000
25%     4.500000   5000.000000
50%     8.000000   7000.000000
75%    11.500000   8500.000000
max    15.000000  11000.000000

In [18]:
dataset.value_counts()

emp_id  emp_name  region  sales_amount
1       Arun      North   5000.0          1
2       Bala      North   9000.0          1
3       Charan    North   7000.0          1
4       Divya     North   4000.0          1
5       Esha      South   6000.0          1
6       Farhan    South   8000.0          1
7       Gokul     South   4000.0          1
8       Hari      South   10000.0         1
9       Indu      East    7000.0          1
10      Jaya      East    3000.0          1
11      Kiran     East    9000.0          1
12      Lakshmi   East    5000.0          1
13      Manoj     West    6000.0          1
14      Nisha     West    11000.0         1
15      Praveen   West    8000.0          1
Name: count, dtype: int64

## Filterting rows

In [5]:
dataset['sales_amount']>2000

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
Name: sales_amount, dtype: bool

## Selecting columns

In [9]:
dataset[['emp_name','region']]

   emp_name region
0      Arun  North
1      Bala  North
2    Charan  North
3     Divya  North
4      Esha  South
5    Farhan  South
6     Gokul  South
7      Hari  South
8      Indu   East
9      Jaya   East
10    Kiran   East
11  Lakshmi   East
12    Manoj   West
13    Nisha   West
14  Praveen   West

## Checking null values in dataset

In [11]:
dataset.isnull().sum()

emp_id          0
emp_name        0
region          0
sales_amount    0
dtype: int64

## group by column and aggregate

In [12]:
dataset.groupby('region')['sales_amount'].mean()

region
East     6000.000000
North    6250.000000
South    7000.000000
West     8333.333333
Name: sales_amount, dtype: float64

## exporting data to csv file

In [13]:
dataset.to_csv('sales_data.csv', index=False)