In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [4]:
df=pd.read_csv("/content/train.csv")

In [ ]:
df['Postal Code'] = df['Postal Code'].astype('Int64')

In [ ]:
df.tail(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [ ]:
print("Null values:",df.isnull().sum())

Null values: Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

## Imputation stratgies when can be used:
 * Mean : Replace the missing value with average of column,this method can be used on Extreme values, columns such as weight, Total_sales, etc.

 * Median: Replace the missing value with middle values, this method is can be used on skewed distrbutions or wiht extreme outliers column.

 * Mode: Replace the missing values with most repeated values, this method can be used on boolean columns, such as gender, yes/no question columns.

 * Forward Fill : Replaces missing values with the previous available value. It is useful when values remain constant, such as a temperature reading between updates.

In [ ]:
##Mean fill
df["Postal Code"].fillna(int(df["Postal Code"].mean()))

0       42420
1       42420
2       90036
3       33311
4       33311
        ...
9795    60610
9796    43615
9797    43615
9798    43615
9799    43615
Name: Postal Code, Length: 9800, dtype: Int64

In [ ]:
##Median fill
df["Postal Code"].fillna(int(df["Postal Code"].median()))

0       42420
1       42420
2       90036
3       33311
4       33311
        ...
9795    60610
9796    43615
9797    43615
9798    43615
9799    43615
Name: Postal Code, Length: 9800, dtype: Int64

In [ ]:
##Mean fill
df["Postal Code"].fillna(int(df["Postal Code"].mode()))

/tmp/ipykernel_4515/2793261868.py:2: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  df["Postal Code"].fillna(int(df["Postal Code"].mode()))

0       42420
1       42420
2       90036
3       33311
4       33311
        ...
9795    60610
9796    43615
9797    43615
9798    43615
9799    43615
Name: Postal Code, Length: 9800, dtype: Int64

In [ ]:
## Forward fill
df["Postal Code"].ffill()

0       42420
1       42420
2       90036
3       33311
4       33311
        ...
9795    60610
9796    43615
9797    43615
9798    43615
9799    43615
Name: Postal Code, Length: 9800, dtype: Int64

In [ ]:
## Calculating the Q1 and Q3 quartiles
Q1 = df['Sales'].quantile(0.25)
Q3 = df['Sales'].quantile(0.75)

In [ ]:
#Calculating Inter quartile range
IQR = Q3 - Q1

# setting upper and lower bound
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

In [ ]:
# Removing outliers using upper and lower bound
df_clean = df[
    (df['Sales'] >= lower_bound) & (df['Sales'] <= upper_bound)
]

In [ ]:
df_clean.tail(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [ ]:
## To remove Extra space btw Starting and ending of values
df['Product Name'].str.strip()

0                       Bush Somerset Collection Bookcase
1       Hon Deluxe Fabric Upholstered Stacking Chairs,...
2       Self-Adhesive Address Labels for Typewriters b...
3           Bretford CR4500 Series Slim Rectangular Table
4                          Eldon Fold 'N Roll Cart System
                              ...
9795    Cardinal HOLDit! Binder Insert Strips,Extra St...
9796             BIC Brite Liner Highlighters, Chisel Tip
9797                                          GE 30524EE4
9798             Anker 24W Portable Micro USB Car Charger
9799                  SanDisk Cruzer 4 GB USB Flash Drive
Name: Product Name, Length: 9800, dtype: object

In [ ]:
## To convert all the values to lowercase
df['Product Name'].str.lower()

0                       BUSH SOMERSET COLLECTION BOOKCASE
1       HON DELUXE FABRIC UPHOLSTERED STACKING CHAIRS,...
2       SELF-ADHESIVE ADDRESS LABELS FOR TYPEWRITERS B...
3           BRETFORD CR4500 SERIES SLIM RECTANGULAR TABLE
4                          ELDON FOLD 'N ROLL CART SYSTEM
                              ...
9795    CARDINAL HOLDIT! BINDER INSERT STRIPS,EXTRA ST...
9796             BIC BRITE LINER HIGHLIGHTERS, CHISEL TIP
9797                                          GE 30524EE4
9798             ANKER 24W PORTABLE MICRO USB CAR CHARGER
9799                  SANDISK CRUZER 4 GB USB FLASH DRIVE
Name: Product Name, Length: 9800, dtype: object

In [ ]:
##To convert all the values to uppercase
df['Product Name'].str.upper()

0                       BUSH SOMERSET COLLECTION BOOKCASE
1       HON DELUXE FABRIC UPHOLSTERED STACKING CHAIRS,...
2       SELF-ADHESIVE ADDRESS LABELS FOR TYPEWRITERS B...
3           BRETFORD CR4500 SERIES SLIM RECTANGULAR TABLE
4                          ELDON FOLD 'N ROLL CART SYSTEM
                              ...
9795    CARDINAL HOLDIT! BINDER INSERT STRIPS,EXTRA ST...
9796             BIC BRITE LINER HIGHLIGHTERS, CHISEL TIP
9797                                          GE 30524EE4
9798             ANKER 24W PORTABLE MICRO USB CAR CHARGER
9799                  SANDISK CRUZER 4 GB USB FLASH DRIVE
Name: Product Name, Length: 9800, dtype: object

In [ ]:
# Replace values
df['Country'].replace({
    'United States': 'US'
})

0       US
1       US
2       US
3       US
4       US
        ..
9795    US
9796    US
9797    US
9798    US
9799    US
Name: Country, Length: 9800, dtype: object

In [5]:
# Create an empty list for the data quality log
quality_log = []

#Check dataset size
quality_log.append({
    "Check": "Dataset Size",
    "Finding": f"{df.shape[0]} rows and {df.shape[1]} columns",
    "Action": "Recorded dataset dimensions"
})

#Check missing values
for col in df.columns:
    missing = df[col].isnull().sum()

    if missing > 0:
        quality_log.append({
            "Check": "Missing Values",
            "Finding": f"{col}: {missing} missing values",
            "Action": "Investigate and handle missing values"
        })

#Check duplicate rows
duplicates = df.duplicated().sum()

quality_log.append({
    "Check": "Duplicate Rows",
    "Finding": f"{duplicates} duplicate rows",
    "Action": (
        "Remove duplicates if inappropriate"
        if duplicates > 0
        else "No action needed"
    )
})

#Check data types
for col in df.columns:
    quality_log.append({
        "Check": "Data Type",
        "Finding": f"{col}: {df[col].dtype}",
        "Action": "Verify the expected data type"
    })

#Check string inconsistencies
text_columns = df.select_dtypes(
    include=["object", "string"]
).columns

for col in text_columns:
    values = df[col].dropna().astype(str)

    whitespace = (values != values.str.strip()).sum()
    inconsistent_case = (
        values != values.str.lower()
    ).sum()

    if whitespace > 0:
        quality_log.append({
            "Check": "Whitespace",
            "Finding": f"{col}: {whitespace} values have extra surrounding spaces",
            "Action": "Strip leading and trailing spaces"
        })

    if inconsistent_case > 0:
        quality_log.append({
            "Check": "Casing",
            "Finding": f"{col}: {inconsistent_case} values are not lowercase",
            "Action": "Review and standardize casing if appropriate"
        })

#Check outliers using the IQR method
numeric_columns = df.select_dtypes(
    include="number"
).columns

for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = (
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ).sum()

    quality_log.append({
        "Check": "Outliers (IQR)",
        "Finding": f"{col}: {outliers} potential outliers",
        "Action": "Investigate before removing"
    })

#Convert the log into a DataFrame
log_df = pd.DataFrame(quality_log)

#Export the log to Excel
log_df.to_excel(
    "data_quality_log.xlsx",
    index=False
)

print(log_df)
print("Data quality log exported successfully!")

             Check                                       Finding  \
0     Dataset Size                      9800 rows and 18 columns
1   Missing Values                Postal Code: 11 missing values
2   Duplicate Rows                              0 duplicate rows
3        Data Type                                 Row ID: int64
4        Data Type                              Order ID: object
5        Data Type                            Order Date: object
6        Data Type                             Ship Date: object
7        Data Type                             Ship Mode: object
8        Data Type                           Customer ID: object
9        Data Type                         Customer Name: object
10       Data Type                               Segment: object
11       Data Type                               Country: object
12       Data Type                                  City: object
13       Data Type                                 State: object
14       Data Type                          Postal Code: float64
15       Data Type                                Region: object
16       Data Type                            Product ID: object
17       Data Type                              Category: object
18       Data Type                          Sub-Category: object
19       Data Type                          Product Name: object
20       Data Type                                Sales: float64
21          Casing       Order ID: 9800 values are not lowercase
22          Casing      Ship Mode: 9800 values are not lowercase
23          Casing    Customer ID: 9800 values are not lowercase
24          Casing  Customer Name: 9800 values are not lowercase
25          Casing        Segment: 9800 values are not lowercase
26          Casing        Country: 9800 values are not lowercase
27          Casing           City: 9800 values are not lowercase
28          Casing          State: 9800 values are not lowercase
29          Casing         Region: 9800 values are not lowercase
30          Casing     Product ID: 9800 values are not lowercase
31          Casing       Category: 9800 values are not lowercase
32          Casing   Sub-Category: 9800 values are not lowercase
33          Casing   Product Name: 9794 values are not lowercase
34  Outliers (IQR)                  Row ID: 0 potential outliers
35  Outliers (IQR)             Postal Code: 0 potential outliers
36  Outliers (IQR)                Sales: 1145 potential outliers

                                          Action
0                    Recorded dataset dimensions
1          Investigate and handle missing values
2                               No action needed
3                  Verify the expected data type
4                  Verify the expected data type
5                  Verify the expected data type
6                  Verify the expected data type
7                  Verify the expected data type
8                  Verify the expected data type
9                  Verify the expected data type
10                 Verify the expected data type
11                 Verify the expected data type
12                 Verify the expected data type
13                 Verify the expected data type
14                 Verify the expected data type
15                 Verify the expected data type
16                 Verify the expected data type
17                 Verify the expected data type
18                 Verify the expected data type
19                 Verify the expected data type
20                 Verify the expected data type
21  Review and standardize casing if appropriate
22  Review and standardize casing if appropriate
23  Review and standardize casing if appropriate
24  Review and standardize casing if appropriate
25  Review and standardize casing if appropriate
26  Review and standardize casing if appropriate
27  Review and standardize casing if appropriate
28  Review and standardize casing if appropriate
29  Review and standardize casing if appropriate
30  Review and standardize casing if appropriate
31  Review and standardize casing if appropriate
32  Review and standardize casing if appropriate
33  Review and standardize casing if appropriate
34                   Investigate before removing
35                   Investigate before removing
36                   Investigate before removing
Data quality log exported successfully!